#
#
# Image for compiling full Arch filesystem in /archlinux.tar.xz.
#
# Given a {{BASE}} image with a functional arch below, this allows
# bootstrapping a new Docker image with no other dependencies than Docker.
#
FROM {{BASE}}

# TODO(hkjn): Try using the same pacman.conf in the bootstrap image as
# well (currently only used within the chroot environment for the new
# install).
COPY pacman.conf /etc/pacman_chroot.conf
WORKDIR /usr/local/bin/
COPY build_arch_fs.sh ./

ENTRYPOINT ["build_arch_fs.sh"]
